### ISSUE TITLE
test

### ISSUE THREAD

**Issue by RealFooney** [CraftRealm/management#21]
testing

**Comment by ar00n** [comment]
Solved this by doing this and this and that.

**Comment by AngelInTheHeaven** [comment]
cool

**Comment by ar00n** [comment]
@AngelInTheHeaven just making sure he can use it, will be helping on the server :)

**Comment by AngelInTheHeaven** [comment]
what
can you speak properly

**Comment by ar00n** [comment]
@RealFooney will be helping out with the server so I wanna make sure he is able to use the issues and board and manage it. :)

**Comment by AngelInTheHeaven** [comment]
okay now i understand :)
