### ISSUE TITLE
Referral system for friends + streamers.

### ISSUE THREAD

**Issue by ar00n** [CraftRealm/management#23]
Comment any suggestions for rewards / incentives for those inviting friends. For example having a code to give to viewers or friends to enter when joining.

Cc: @RealFooney

**Comment by AngelInTheHeaven** [comment]
rewards for voting or?

**Comment by ar00n** [comment]
> rewards for voting or?

Updated issue with better definition.

**Comment by AngelInTheHeaven** [comment]
i mean the obvious answer is diamonds or money for rewards for asking out friends to join and play

**Comment by ar00n** [comment]
Moved to https://github.com/CraftRealm/management/discussions/24#discussion-3799004
