### ISSUE TITLE
Auction house doesn't work when talking to suda

### ISSUE THREAD

**Issue by AngelInTheHeaven** [CraftRealm/management#35]
https://user-images.githubusercontent.com/44226891/149657953-719f13c1-2bdf-4e5b-941d-7857588535d2.mp4

**Comment by ar00n** [comment]
Will have to look into auctionhouse, whether it's wanted or not. Or to just have trading between players and shop plots etc.

**Comment by ar00n** [comment]
Moved to discussion: https://github.com/CraftRealm/management/discussions/38
